### ISSUE TITLE
Rename the module from Cauli to something different to be able to use it as a namespace

### ISSUE THREAD

**Issue by brototyp** [cauliframework/cauli#135]
Currently the framework is called `Cauli` as well as one class within the framework. This makes the module-namespace unusable. If one for example wants to use `Cauli.Configuration` the swift compiler interpretes `Cauli` as the class and thus it will not compile.

My proposal ist to rename the framework and module to `Cauliframework`.

**Comment by pstued** [comment]
Works for me.

And just for keeping track, there‘s also a ticket for the Swift team:
https://bugs.swift.org/browse/SR-5304
