### ISSUE TITLE
Allow users to modify records before storing them

### ISSUE THREAD

**Issue by Shukuyen** [cauliframework/cauli#143]
**As a user I want to anonymize some aspects of a request or response when it is displayed by a presentation floret.**

Example: 
> I want to give beta users access to the Inspector Floret for better bug reports, but I don't want them to be able to see some authentication information contained in the request.

Modifications should not affect actual network requests, but only the presentation layer in Cauli florets. Hence the suggestion by @brototyp to add a pre-serialize hook to the `Configuration` that is able to modify a `Record` before it is saved.

**Comment by brototyp** [comment]
This was implemented in #146
