### ISSUE TITLE
Add an optional description parameter to the Floret protocol

### ISSUE THREAD

**Issue by brototyp** [cauliframework/cauli#176]
When writing a Floret, sometimes the name of a floret isn't enough to describe what the floret doesn't and how it should be used.

I propose to add an optional `var description: String? { get }` parameter to the `Floret` protocol that can be used to describe a floret in greater detail. This parameter is then displayed under the name of a floret in the `InspectorViewController`.

Open question: What should we do if a `Floret` appears twice in the `InspectorViewController` because it is an Intercepting- as well as a DisplayingFloret?

**Comment by pstued** [comment]
What do you think when we add the description rather to the `InspectingFloret` and `DisplayingFloret` protocol? Then a floret can describe each section.

**Comment by brototyp** [comment]
As discussed: Let's go with a single description for now and revisit the Floret Protocols in general somewhen in the future.
