### ISSUE TITLE
Ignore all network requests when Cauli is disabled

### ISSUE THREAD

**Issue by pstued** [cauliframework/cauli#185]
### Reproduction
1. Create a custom Cauli instance
2. Run that instance
3. Pause that instance

### Expected behavior
The CauliURLProtocol won't take care of future network requests. Which means that the network code of an app works without any Cauli interference.

### Observed behavior
If Cauli is paused, the `CauliURLProtocol` will still take care of the network requests and just won't pass the request and responses to the Florets.

**Comment by brototyp** [comment]
@pstued This is fixed in #186, right?

**Comment by pstued** [comment]
Indeed, going to close it.
