### ISSUE TITLE
Add fallback value for configuration parameter to Cauli class

### ISSUE THREAD

**Issue by lukaswuerzburger** [cauliframework/cauli#189]
### Suggestion

For convenience I suggest to get rid of the required configuration parameter and fallback to the standard configuration. It is just less setup code if you only want to use the default setup or only your own florets.

### Callside

**Before:**
```
let cauli = Cauli([InspectorFloret()], configuration: Configuration.standard)
```

**After:**
```
let cauli = Cauli([InspectorFloret()])
```

**Comment by brototyp** [comment]
This is implemented and merged and will be part of the next release.
