### ISSUE TITLE
'NSObject.hashValue' is not overridable; did you mean to override 'NSObject.hash'?

### ISSUE THREAD

**Issue by lukaswuerzburger** [cauliframework/cauli#191]
Nimble > Predicate.swift > line 314

```
public override var hashValue: Int { return self.status.hashValue }
                    ^
```
> 'NSObject.hashValue' is not overridable; did you mean to override 'NSObject.hash'?

Running the unit test is not possible. However, updating pods fixes the problem.

Environment:
- macOS 10.14.5 (18F132)
- Xcode 10.2.1 (10E1001)
- Commit 2170924921ce3efcf6079821dd51d41973c28ba7

**Comment by brototyp** [comment]
Nice. Do you mind creating a PR with the updated Podfile.lock?

**Comment by lukaswuerzburger** [comment]
Ok, first I wasn't sure about who wants to have control over the pods. At the end you have it anyway.

I guess I should also include not only the `Podfile.lock` but also the updated source/configuration files that chaged during `pod update` right?

**Comment by brototyp** [comment]
I guess we are super relaxed in this regard, esp. since the Pods aren't "real" dependencies. But I would love to have a "correct" set of pods in the repo.

Yeah, please include the Pods folder as well.

**Comment by lukaswuerzburger** [comment]
#192 there you go
