### ISSUE TITLE
UIWebView not loading assets after redirect

### ISSUE THREAD

**Issue by lukaswuerzburger** [cauliframework/cauli#196]
I'm experiencing loading issues in a `UIWebView` after coming from a redirect. 

**These are the steps my app goes through:**
1. The app requests a URL that immediatley redirects to another URL.
2. The redirected page loads, but no additional requests are made like e.g. loading CSS or Javascript files.

I don't even use any florets in my Cauli setup:

```swift
let cauli = Cauli([], configuration: .standard)
cauli.run()
```

If the app requests the redirected URL directly, it actually loads the CSS. But this is of course not possible in a real life scenario for my app (oauth flow).

In the picture on the left side you can see the version with a call that redirects. On the right side without redirect.

![xing-bug](https://user-images.githubusercontent.com/10812458/64548367-c5ae4680-d32e-11e9-95b0-9119f233185b.jpg)

This is also reproducible on a local machine. 

1. Create a test directory with a php file **index.php** in it:
```php
<?php
header("Location: https://google.com/");
?>
```

2. Start a PHP server in that directory:
```sh
php -S 0.0.0.0:8888
```

3. Use the test project that i've created: https://github.com/lukaswuerzburger/cauli-redirect-bug/ Don't forget to use your IP address here: https://github.com/lukaswuerzburger/cauli-redirect-bug/blob/14e45beec3d261a5abf68bdb1c32f1bdca58852d/cauli-redirect-bug/ViewController.swift#L17

**Comment by brototyp** [comment]
Hey @lukaswuerzburger, thanks for the splendid bug report. It really helped to nail down this issue.
I think I found a fix for it. Can you have a look at this PR and verify it's working? #211

**Comment by lukaswuerzburger** [comment]
I've tested it on several iOS versions and clicked around and it works just fine 🎉

**Comment by brototyp** [comment]
> I've tested it on several iOS versions and clicked around and it works just fine 🎉

Sweet. Thanks a lot!
