### ISSUE TITLE
Can't install via Swift Package Manager

### ISSUE THREAD

**Issue by lukaswuerzburger** [cauliframework/cauli#217]
This fails because the Package.swift was added after the last tag. So version 1.0.1 currently has no Package.swift file

![Screen Shot 2021-03-11 at 17 13 41](https://user-images.githubusercontent.com/10812458/110818128-45eb9a00-828d-11eb-8a9d-c0c352be87cf.png)
![Screen Shot 2021-03-11 at 17 13 47](https://user-images.githubusercontent.com/10812458/110818136-48e68a80-828d-11eb-9628-d7356282f4bf.png)

**Comment by brototyp** [comment]
This is **finally** fixed. The latest version, 1.1.0, can be installed via SPM.
